### ISSUE TITLE
Unit tests fail sporadically 

### ISSUE THREAD

**Issue by witwit** [SemkoDev/nelson.cli#1]
Sometimes heart-test.js fails with:
Using Ubuntu 16.04
node -v: 9.1.0

```
 FAIL  src/node/__tests__/heart-test.js (23.599s)
  ● Heart › updates personality correctly

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:64:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:478:11)
      at tryOnTimeout (timers.js:302:5)
      at Timer.listOnTimeout (timers.js:262:5)

```

FYI @romansemko

**Comment by romansemko** [comment]
Need to increase timeout, I guess. Depends on the power of your machine.

**Comment by romansemko** [comment]
Should be fixed.
