### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL: nelson1.carriota.com/14600

### ISSUE THREAD

**Issue by witwit** [SemkoDev/nelson.cli#2]
Ubuntu 16.04
node -v: 9.1.0

How to reproduce:
`yarn make`
`node ./dist/nelson.js --neighbors nelson1.carriota.com/14600 nelson2.carriota.com/14600`

Error throws:
```
TypeError [ERR_INVALID_URL]: Invalid URL: nelson1.carriota.com/14600
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at /home/wit/Dev/nelson.cli/dist/nelson.js:23:16
    at Array.map (<anonymous>)
    at parseNeighbors (/home/wit/Dev/nelson.cli/dist/nelson.js:22:27)
    at Command.<anonymous> (/home/wit/Dev/nelson.cli/node_modules/commander/index.js:394:35)
    at emitOne (events.js:125:13)
    at Command.emit (events.js:221:7)
    at Command.parseOptions (/home/wit/Dev/nelson.cli/node_modules/commander/index.js:719:14)

```

**Comment by romansemko** [comment]
Should be fixed now
