### ISSUE TITLE
Connection errors running Nelson without neighbours

### ISSUE THREAD

**Issue by witwit** [SemkoDev/nelson.cli#4]
Ubuntu 16.04
node -v: 9.1.0

reproduce:
1. tried to use nelson, but failed with error as reported in #2 
2. `node ./src/nelson.js`

Gives an output:

```
node ./src/nelson.js
1512730999739 16600::LIST  db and default peers loaded
1512730999741 16600::NODE  server created...
1512730999742 16600::HEART Cycle/epoch intervals: 60 300
1512730999742 16600::HEART new personality f 722ab289eb1a6b044fdfe2640085f15e341abcb64fb00f26604b12ffcde5cd93e0e885315e0cb8511f3a1115ae59d23b
1512730999743 16600::NODE  connecting peer http: null
1512730999745 16600::NODE  connecting peer https: null
1512730999746 16600::NODE  initialized!
1512730999748 16600::LIST  updated peer http::null { hostname: 'http:',
  ip: null,
  port: null,
  TCPPort: null,
  UDPPort: 14600,
  seen: 1,
  connected: 0,
  tried: 0,
  weight: 1,
  dateTried: null,
  dateLastConnected: null,
  isTrusted: true }
1512730999750 16600::LIST  updated peer https::null { hostname: 'https:',
  ip: null,
  port: null,
  TCPPort: null,
  UDPPort: 14600,
  seen: 1,
  connected: 0,
  tried: 0,
  weight: 1,
  dateTried: null,
  dateLastConnected: null,
  isTrusted: true }
1512730999755 16600::NODE  closing connection { Error: getaddrinfo ENOTFOUND http http:80
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http',
  host: 'http',
  port: 80 }
1512730999756 16600::NODE  removing neighbor http: null
1512730999756 16600::NODE  removing neighbors
1512730999756 16600::IRI   Neighbors removed [ 'http://http::null' ]
1512730999757 16600::NODE  closing connection 1006
1512730999757 16600::NODE  removing neighbor http: null
1512730999757 16600::NODE  removing neighbors
1512730999757 16600::IRI   Neighbors removed [ 'http://http::null' ]
1512730999758 16600::NODE  closing connection { Error: getaddrinfo ENOTFOUND https https:80
    at errnoException (dns.js:55:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https',
  host: 'https',
  port: 80 }
1512730999758 16600::NODE  removing neighbor https: null
1512730999758 16600::NODE  removing neighbors
1512730999758 16600::IRI   Neighbors removed [ 'http://https::null' ]
1512730999758 16600::NODE  closing connection 1006
1512730999742 16600::HEART new personality f 722ab289eb1a6b044fdfe2640085f15e341abcb64fb00f26604b12ffcde5cd93e0e885315e0cb85[58/4750]
ae59d23b
1512730999743 16600::NODE  connecting peer http: null
1512730999745 16600::NODE  connecting peer https: null
1512730999746 16600::NODE  initialized!
1512730999748 16600::LIST  updated peer http::null { hostname: 'http:',
  ip: null,
  port: null,
  TCPPort: null,
  UDPPort: 14600,
  seen: 1,
  connected: 0,
  tried: 0,
  weight: 1,
  dateTried: null,
  dateLastConnected: null,
  isTrusted: true }
1512730999750 16600::LIST  updated peer https::null { hostname: 'https:',
  ip: null,
  port: null,
  TCPPort: null,
  UDPPort: 14600,
  seen: 1,
  connected: 0,
  tried: 0,
  weight: 1,
  dateTried: null,
  dateLastConnected: null,
  isTrusted: true }
1512730999755 16600::NODE  closing connection { Error: getaddrinfo ENOTFOUND http http:80
... continues forever
```

**Comment by witwit** [comment]
This can be fixed by removing `data/neighbours.db`, which held corrupt data in this case.

**Comment by romansemko** [comment]
Yup, the corrupted data was originated from #2 . This should be fixed now.
